name: Build and push gem to Github Packages

on:
  push:
    branches:
      - main 
    paths:
      - lib/shoulda/matchers/version.rb

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.1.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
      - run: bundle install
      - name: Publish to Github Packages
        run: |
          gem build *.gemspec
          mkdir ~/.gem
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" > ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          gem push *.gem --key github --host https://rubygems.pkg.github.com/Flatbook
